### ISSUE TITLE
my 3d print is Z5fm2 15:49:00.947 : Serial COM erro:System.IO.Ports.SerialErrorReceivedEventArgs and 15:49:00.970 : Error:EEPROM CRC mismatch - (stored) 63187 != 52708 (calculated)! 

### ISSUE THREAD

**Issue by LUIZ-RODRIGUES-ANDRADE** [ZONESTAR3D/Z6#1]
5:49:00.947 : Serial COM erro:System.IO.Ports.SerialErrorReceivedEventArgs
15:49:00.957 : Printer reset detected - initalizing
15:49:00.957 : start
15:49:00.957 : echo: External Reset
15:49:00.957 : Marlin Base on Marlin1.1.8
15:49:00.957 : echo: Last Updated: 2018-10-01 | Author: (Hally@ZONESTAR)
15:49:00.957 : echo:Compiled: Oct 20 2018
15:49:00.957 : echo: Free Memory: 11693 PlannerBufferBytes: 1360
15:49:00.970 : Error:EEPROM CRC mismatch - (stored) 63187 != 52708 (calculated)!
15:49:01.014 : echo:Hardcoded Default Settings Loaded
15:49:01.014 : echo: G21 ; Units in mm
15:49:01.014 : echo: M149 C ; Units in Celsius
15:49:01.014 : echo:Filament settings: Disabled
15:49:01.014 : echo: M200 D1.75
15:49:01.014 : echo: M200 D0
15:49:01.014 : echo:Steps per unit:
15:49:01.014 : echo: M92 X80.00 Y80.00 Z400.00 E85.00
15:49:01.014 : echo:Maximum feedrates (units/s):
15:49:01.014 : echo: M203 X150.00 Y100.00 Z8.00 E50.00
15:49:01.014 : echo:Maximum Acceleration (units/s2):
15:49:01.014 : echo: M201 X2000 Y800 Z100 E5000
15:49:01.014 : echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
15:49:01.014 : echo: M204 P500.00 R500.00 T1000.00
15:49:01.039 : echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
15:49:01.039 : echo: M205 S0.00 T0.00 B20000 X10.00 Y10.00 Z2.70 E5.00
15:49:01.039 : echo:Material heatup parameters:
15:49:01.039 : echo: M145 S0 H190 B50 F0
15:49:01.039 : echo: M145 S1 H240 B100 F0
15:49:01.039 : echo:PID settings:
15:49:01.039 : echo: M301 P46.80 I3.86 D141.85
15:49:01.171 : N1 M11034
15:49:01.171 : N2 M11536
15:49:01.171 : N3 M10536
15:49:01.171 : N4 M11435
15:49:01.175 : N5 M111 S698
15:49:01.177 : N6 T060
15:49:01.177 : N7 M2022
15:49:01.180 : N8 M8019
15:49:01.180 : N9 M10546
15:49:04.072 : ok
15:49:04.239 : N10 M10522
15:49:04.588 : N11 M2033
15:49:04.603 : echo:SD card ok
15:49:04.648 : FIRMWARE_NAME:Marlin Base on Marlin1.1.8 (Github) SOURCE_CODE_URL:https://github.com/zonestar3d PROTOCOL_VERSION:1.0 MACHINE_TYPE:Z5NM2 EXTRUDER_COUNT:1 UUID:00000010-0808-0003-0000-20180110001
15:49:04.648 : Cap:SERIAL_XON_XOFF:0
15:49:04.650 : Cap:EEPROM:1
15:49:04.650 : Cap:VOLUMETRIC:1
15:49:04.650 : Cap:AUTOREPORT_TEMP:1
15:49:04.650 : Cap:PROGRESS:0
15:49:04.650 : Cap:PRINT_JOB:1
15:49:04.650 : Cap:AUTOLEVEL:0
15:49:04.650 : Cap:Z_PROBE:0
15:49:04.650 : Cap:LEVELING_DATA:0
15:49:04.650 : Cap:BUILD_PERCENT:0
15:49:04.650 : Cap:SOFTWARE_POWER:0
15:49:04.650 : Cap:TOGGLE_LIGHTS:0
15:49:04.650 : Cap:CASE_LIGHT_BRIGHTNESS:0
15:49:04.650 : Cap:EMERGENCY_PARSER:0
15:49:04.650 : ok
15:49:04.651 : N12 M220 S10082
15:49:04.670 : ok T:26.75 /0.00 B:26.72 /0.00 @:0 B@:0
15:49:04.685 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
15:49:04.685 : ok
15:49:04.685 : N13 M221 S10082
15:49:04.702 : echo:DEBUG:INFO,ERRORS
15:49:04.702 : ok
15:49:04.702 : ok
15:49:04.702 : Begin file list
15:49:04.702 : N14 M111 S682
15:49:04.705 : N15 T014
15:49:04.726 : CFFFP_~1.GCO 5055174
15:49:04.734 : End file list
15:49:04.734 : ok
15:49:04.734 : ok
15:49:04.735 : N16 M155 S187
15:49:04.736 : ok T:26.75 /0.00 B:26.72 /0.00 @:0 B@:0
15:49:04.740 : ok T:26.75 /0.00 B:26.72 /0.00 @:0 B@:0
15:49:04.741 : Begin file list
15:49:04.764 : CFFFP_~1.GCO 5055174
15:49:04.770 : End file list
15:49:04.770 : ok
15:49:04.770 : ok
15:49:04.774 : ok
15:49:04.774 : echo:DEBUG:INFO,ERRORS
15:49:04.774 : ok
15:49:04.774 : ok
15:49:04.774 : ok
15:49:05.778 : T:27.00 /0.00 B:26.62 /0.00 @:0 B@:0
15:49:06.784 : T:27.00 /0.00 B:26.70 /0.00 @:0 B@:0
15:49:07.777 : T:27.00 /0.00 B:26.67 /0.00 @:0 B@:0
![Repetier-Host V2 0 5 11_10_2020 15_55_40](https://user-images.githubusercontent.com/72706809/95687560-ad1bfa00-0bda-11eb-9c75-dd2315bf3364.png)
![Repetier-Host V2 0 5 11_10_2020 13_55_53](https://user-images.githubusercontent.com/72706809/95687561-ae4d2700-0bda-11eb-923c-5eb346a7b83d.png)
![Repetier-Host V2 0 5 11_10_2020 15_55_23](https://user-images.githubusercontent.com/72706809/95687562-ae4d2700-0bda-11eb-923a-f1c78929ed6a.png)
![Repetier-Host V2 0 5 11_10_2020 15_55_33](https://user-images.githubusercontent.com/72706809/95687564-aee5bd80-0bda-11eb-9a15-7309a080eb3c.png)

**Comment by ZONESTAR3D** [comment]
I think these problems are about repeater host and Marlin firmware compatibility. You can ignore these issue.

In addition, we will upload the firmware of Z5 Series in the next several days. The new firmware will be based on marlin2.0. X. please continue to pay attention to us, thank you very much!

**Comment by LUIZ-RODRIGUES-ANDRADE** [comment]
esse problema ocorre ate com card sd. a impressora começa a imprimir porem para no meio, da mesma forma acontece no repetier host.

**Comment by LUIZ-RODRIGUES-ANDRADE** [comment]
> Acho que esses problemas são sobre a compatibilidade do host repetidor e do firmware Marlin. Você pode ignorar esses problemas.
> 
> Além disso, faremos o upload do firmware do Z5 Series nos próximos dias. O novo firmware será baseado no marlin2.0. X. continue prestando atenção em nós, muito obrigado!

esse problema afeta a impressão ate no sd card

**Comment by LUIZ-RODRIGUES-ANDRADE** [comment]
tem como me ajudar ???

**Comment by LUIZ-RODRIGUES-ANDRADE** [comment]
esse problema afeta a impressão ate com o  cartão SD

**Comment by LUIZ-RODRIGUES-ANDRADE** [comment]
esse problema afeta a impressão ate no cartão SD

**Comment by LUIZ-RODRIGUES-ANDRADE** [comment]
esse problema afeta a impressão ate no cartão SD

**Comment by LUIZ-RODRIGUES-ANDRADE** [comment]
como fazer o update da z5fm2 ?

**Comment by ZONESTAR3D** [comment]
Please translate the message to English before send the message, thanks!
